version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: nextjs_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    restart: always